// @title           Weather Dashboard API
// @version         1.0
// @description     Погодный дашборд — Go backend с Open-Meteo (без API-ключей)
// @host            localhost:8080
// @BasePath        /
// @schemes         http
package main

import (
	"log"
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/go-chi/chi/v5/middleware"
	"github.com/go-chi/cors"
	"github.com/joho/godotenv"
	httpSwagger "github.com/swaggo/http-swagger"

	_ "github.com/13axiom/weather-api/docs" // generated by: swag init -g cmd/server/main.go
	"github.com/13axiom/weather-api/internal/client"
	"github.com/13axiom/weather-api/internal/config"
	"github.com/13axiom/weather-api/internal/database"
	"github.com/13axiom/weather-api/internal/handler"
	"github.com/13axiom/weather-api/internal/service"
)

func main() {
	// Load .env file (error is ignored — in CI/production, vars come from environment)
	_ = godotenv.Load()

	cfg := config.Load()

	// Connect to PostgreSQL
	db, err := database.New(cfg.DatabaseURL)
	if err != nil {
		log.Fatalf("failed to connect to database: %v", err)
	}
	defer db.Close()

	// Run migrations (CREATE TABLE IF NOT EXISTS — safe to run every startup)
	if err := db.Migrate(); err != nil {
		log.Fatalf("migration failed: %v", err)
	}

	// Wire up services
	meteoClient := client.New()
	weatherSvc  := service.NewWeatherService(db)
	syncSvc     := service.NewSyncService(db, meteoClient, cfg.SyncInterval(), cfg.DefaultCities)

	// Start background sync goroutine
	syncSvc.Start()

	// Wire up handlers
	weatherH := handler.NewWeatherHandler(weatherSvc)
	syncH    := handler.NewSyncHandler(syncSvc)

	// Set up router
	r := chi.NewRouter()
	r.Use(middleware.Logger)
	r.Use(middleware.Recoverer)
	r.Use(cors.Handler(cors.Options{
		AllowedOrigins: cfg.AllowedOrigins,
		AllowedMethods: []string{"GET", "POST", "OPTIONS"},
		AllowedHeaders: []string{"Content-Type", "Accept"},
	}))

	// Health check
	r.Get("/health", func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.Write([]byte(`{"status":"ok"}`))
	})

	// Swagger UI — http://localhost:8080/swagger/index.html
	// Generate docs first: swag init -g cmd/server/main.go --output docs
	r.Get("/swagger/*", httpSwagger.WrapHandler)

	// API v1
	r.Route("/api/v1", func(r chi.Router) {
		r.Get("/cities",          weatherH.GetCities)
		r.Get("/weather/{city}", weatherH.GetWeather)
		r.Post("/sync",          syncH.TriggerSync)
	})

	log.Printf("🌤  Weather API started on :%s  (sync every %v)", cfg.Port, cfg.SyncInterval())
	log.Printf("📖  Swagger UI: http://localhost:%s/swagger/index.html", cfg.Port)
	log.Fatal(http.ListenAndServe(":"+cfg.Port, r))
}
